// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.12.
// **********************************************************************

#ifndef __GAMEDEMOBASE_H_
#define __GAMEDEMOBASE_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace GameDemo
{
    const tars::Int32 SUCC = 0;

    const tars::Int32 ERR_ACCOUNT_EXISTS = 1001;

    const tars::Int32 ERR_ACCOUNT_NOT_EXISTS = 1002;

    const tars::Int32 ERR_PASSWORD_MISMATCH = 1003;

    const tars::Int32 ERR_ROLE_EXISTS = 2001;

    const tars::Int32 ERR_ROLE_NOT_EXISTS = 2002;

    const tars::Int32 ERR_DB_ERROR = 5001;

    const tars::Int32 ERR_SERVER_BUSY = 9999;

    struct AccountInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.AccountInfo";
        }
        static string MD5()
        {
            return "5a67f4fb1c9184a7f3f53202ae723d54";
        }
        AccountInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            id = 0;
            qqNumber = "";
            password = "";
            createTime = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(id, 0);
            _os.write(qqNumber, 1);
            _os.write(password, 2);
            _os.write(createTime, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(id, 0, true);
            _is.read(qqNumber, 1, true);
            _is.read(password, 2, true);
            _is.read(createTime, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["id"] = tars::JsonOutput::writeJson(id);
            p->value["qqNumber"] = tars::JsonOutput::writeJson(qqNumber);
            p->value["password"] = tars::JsonOutput::writeJson(password);
            p->value["createTime"] = tars::JsonOutput::writeJson(createTime);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(id,pObj->value["id"], true);
            tars::JsonInput::readJson(qqNumber,pObj->value["qqNumber"], true);
            tars::JsonInput::readJson(password,pObj->value["password"], true);
            tars::JsonInput::readJson(createTime,pObj->value["createTime"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(id,"id");
            _ds.display(qqNumber,"qqNumber");
            _ds.display(password,"password");
            _ds.display(createTime,"createTime");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(id, true);
            _ds.displaySimple(qqNumber, true);
            _ds.displaySimple(password, true);
            _ds.displaySimple(createTime, false);
            return _os;
        }
    public:
        tars::Int64 id;
        std::string qqNumber;
        std::string password;
        tars::Int64 createTime;
    };
    inline bool operator==(const AccountInfo&l, const AccountInfo&r)
    {
        return l.id == r.id && l.qqNumber == r.qqNumber && l.password == r.password && l.createTime == r.createTime;
    }
    inline bool operator!=(const AccountInfo&l, const AccountInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const AccountInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,AccountInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct RoleInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.RoleInfo";
        }
        static string MD5()
        {
            return "1713bb1e5e8960865b513a9a61f97688";
        }
        RoleInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            id = 0;
            accountId = 0;
            roleName = "";
            job = 0;
            level = 0;
            hp = 0;
            mp = 0;
            exp = 0;
            x = 0;
            y = 0;
            sceneId = 0;
            createTime = 0;
            lastLoginTime = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(id, 0);
            _os.write(accountId, 1);
            _os.write(roleName, 2);
            _os.write(job, 3);
            _os.write(level, 4);
            _os.write(hp, 5);
            _os.write(mp, 6);
            _os.write(exp, 7);
            _os.write(x, 8);
            _os.write(y, 9);
            _os.write(sceneId, 10);
            _os.write(createTime, 11);
            _os.write(lastLoginTime, 12);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(id, 0, true);
            _is.read(accountId, 1, true);
            _is.read(roleName, 2, true);
            _is.read(job, 3, true);
            _is.read(level, 4, true);
            _is.read(hp, 5, true);
            _is.read(mp, 6, true);
            _is.read(exp, 7, true);
            _is.read(x, 8, true);
            _is.read(y, 9, true);
            _is.read(sceneId, 10, true);
            _is.read(createTime, 11, true);
            _is.read(lastLoginTime, 12, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["id"] = tars::JsonOutput::writeJson(id);
            p->value["accountId"] = tars::JsonOutput::writeJson(accountId);
            p->value["roleName"] = tars::JsonOutput::writeJson(roleName);
            p->value["job"] = tars::JsonOutput::writeJson(job);
            p->value["level"] = tars::JsonOutput::writeJson(level);
            p->value["hp"] = tars::JsonOutput::writeJson(hp);
            p->value["mp"] = tars::JsonOutput::writeJson(mp);
            p->value["exp"] = tars::JsonOutput::writeJson(exp);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            p->value["createTime"] = tars::JsonOutput::writeJson(createTime);
            p->value["lastLoginTime"] = tars::JsonOutput::writeJson(lastLoginTime);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(id,pObj->value["id"], true);
            tars::JsonInput::readJson(accountId,pObj->value["accountId"], true);
            tars::JsonInput::readJson(roleName,pObj->value["roleName"], true);
            tars::JsonInput::readJson(job,pObj->value["job"], true);
            tars::JsonInput::readJson(level,pObj->value["level"], true);
            tars::JsonInput::readJson(hp,pObj->value["hp"], true);
            tars::JsonInput::readJson(mp,pObj->value["mp"], true);
            tars::JsonInput::readJson(exp,pObj->value["exp"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
            tars::JsonInput::readJson(createTime,pObj->value["createTime"], true);
            tars::JsonInput::readJson(lastLoginTime,pObj->value["lastLoginTime"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(id,"id");
            _ds.display(accountId,"accountId");
            _ds.display(roleName,"roleName");
            _ds.display(job,"job");
            _ds.display(level,"level");
            _ds.display(hp,"hp");
            _ds.display(mp,"mp");
            _ds.display(exp,"exp");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(sceneId,"sceneId");
            _ds.display(createTime,"createTime");
            _ds.display(lastLoginTime,"lastLoginTime");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(id, true);
            _ds.displaySimple(accountId, true);
            _ds.displaySimple(roleName, true);
            _ds.displaySimple(job, true);
            _ds.displaySimple(level, true);
            _ds.displaySimple(hp, true);
            _ds.displaySimple(mp, true);
            _ds.displaySimple(exp, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(sceneId, true);
            _ds.displaySimple(createTime, true);
            _ds.displaySimple(lastLoginTime, false);
            return _os;
        }
    public:
        tars::Int64 id;
        tars::Int64 accountId;
        std::string roleName;
        tars::Int32 job;
        tars::Int32 level;
        tars::Int32 hp;
        tars::Int32 mp;
        tars::Int64 exp;
        tars::Float x;
        tars::Float y;
        tars::Int32 sceneId;
        tars::Int64 createTime;
        tars::Int64 lastLoginTime;
    };
    inline bool operator==(const RoleInfo&l, const RoleInfo&r)
    {
        return l.id == r.id && l.accountId == r.accountId && l.roleName == r.roleName && l.job == r.job && l.level == r.level && l.hp == r.hp && l.mp == r.mp && l.exp == r.exp && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && l.sceneId == r.sceneId && l.createTime == r.createTime && l.lastLoginTime == r.lastLoginTime;
    }
    inline bool operator!=(const RoleInfo&l, const RoleInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const RoleInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,RoleInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerInfo";
        }
        static string MD5()
        {
            return "b8c87114a8776ca3e9b5f58b2648a738";
        }
        PlayerInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            openId = "";
            roleName = "";
            level = 0;
            x = 0;
            y = 0;
            z = 0;
            sceneId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(openId, 1);
            _os.write(roleName, 2);
            _os.write(level, 3);
            _os.write(x, 4);
            _os.write(y, 5);
            _os.write(z, 6);
            _os.write(sceneId, 7);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(openId, 1, true);
            _is.read(roleName, 2, true);
            _is.read(level, 3, true);
            _is.read(x, 4, true);
            _is.read(y, 5, true);
            _is.read(z, 6, true);
            _is.read(sceneId, 7, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["openId"] = tars::JsonOutput::writeJson(openId);
            p->value["roleName"] = tars::JsonOutput::writeJson(roleName);
            p->value["level"] = tars::JsonOutput::writeJson(level);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["z"] = tars::JsonOutput::writeJson(z);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(openId,pObj->value["openId"], true);
            tars::JsonInput::readJson(roleName,pObj->value["roleName"], true);
            tars::JsonInput::readJson(level,pObj->value["level"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(z,pObj->value["z"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(openId,"openId");
            _ds.display(roleName,"roleName");
            _ds.display(level,"level");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(z,"z");
            _ds.display(sceneId,"sceneId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(openId, true);
            _ds.displaySimple(roleName, true);
            _ds.displaySimple(level, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(z, true);
            _ds.displaySimple(sceneId, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        std::string openId;
        std::string roleName;
        tars::Int32 level;
        tars::Float x;
        tars::Float y;
        tars::Float z;
        tars::Int32 sceneId;
    };
    inline bool operator==(const PlayerInfo&l, const PlayerInfo&r)
    {
        return l.playerId == r.playerId && l.openId == r.openId && l.roleName == r.roleName && l.level == r.level && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && tars::TC_Common::equal(l.z,r.z) && l.sceneId == r.sceneId;
    }
    inline bool operator!=(const PlayerInfo&l, const PlayerInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct SceneInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.SceneInfo";
        }
        static string MD5()
        {
            return "38077dd53b3ea7507376586809fd8b92";
        }
        SceneInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sceneId = 0;
            sceneName = "";
            playerCount = 0;
            maxPlayer = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sceneId, 0);
            _os.write(sceneName, 1);
            _os.write(playerCount, 2);
            _os.write(maxPlayer, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sceneId, 0, true);
            _is.read(sceneName, 1, true);
            _is.read(playerCount, 2, true);
            _is.read(maxPlayer, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            p->value["sceneName"] = tars::JsonOutput::writeJson(sceneName);
            p->value["playerCount"] = tars::JsonOutput::writeJson(playerCount);
            p->value["maxPlayer"] = tars::JsonOutput::writeJson(maxPlayer);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
            tars::JsonInput::readJson(sceneName,pObj->value["sceneName"], true);
            tars::JsonInput::readJson(playerCount,pObj->value["playerCount"], true);
            tars::JsonInput::readJson(maxPlayer,pObj->value["maxPlayer"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sceneId,"sceneId");
            _ds.display(sceneName,"sceneName");
            _ds.display(playerCount,"playerCount");
            _ds.display(maxPlayer,"maxPlayer");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sceneId, true);
            _ds.displaySimple(sceneName, true);
            _ds.displaySimple(playerCount, true);
            _ds.displaySimple(maxPlayer, false);
            return _os;
        }
    public:
        tars::Int32 sceneId;
        std::string sceneName;
        tars::Int32 playerCount;
        tars::Int32 maxPlayer;
    };
    inline bool operator==(const SceneInfo&l, const SceneInfo&r)
    {
        return l.sceneId == r.sceneId && l.sceneName == r.sceneName && l.playerCount == r.playerCount && l.maxPlayer == r.maxPlayer;
    }
    inline bool operator!=(const SceneInfo&l, const SceneInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const SceneInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,SceneInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerMoveNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerMoveNotify";
        }
        static string MD5()
        {
            return "674e35bea8eedc87261b47e9db8c2493";
        }
        PlayerMoveNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            x = 0;
            y = 0;
            z = 0;
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(x, 1);
            _os.write(y, 2);
            _os.write(z, 3);
            _os.write(timestamp, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(x, 1, true);
            _is.read(y, 2, true);
            _is.read(z, 3, true);
            _is.read(timestamp, 4, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["z"] = tars::JsonOutput::writeJson(z);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(z,pObj->value["z"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(z,"z");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(z, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Float x;
        tars::Float y;
        tars::Float z;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerMoveNotify&l, const PlayerMoveNotify&r)
    {
        return l.playerId == r.playerId && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && tars::TC_Common::equal(l.z,r.z) && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerMoveNotify&l, const PlayerMoveNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerMoveNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerMoveNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerEnterNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerEnterNotify";
        }
        static string MD5()
        {
            return "fbe6de8dc110a32ba26fec22b22c9ad0";
        }
        PlayerEnterNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            player.resetDefautlt();
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(player, 0);
            _os.write(timestamp, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(player, 0, true);
            _is.read(timestamp, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["player"] = tars::JsonOutput::writeJson(player);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(player,pObj->value["player"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(player,"player");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(player, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        GameDemo::PlayerInfo player;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerEnterNotify&l, const PlayerEnterNotify&r)
    {
        return l.player == r.player && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerEnterNotify&l, const PlayerEnterNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerEnterNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerEnterNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerLeaveNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerLeaveNotify";
        }
        static string MD5()
        {
            return "fbee022731165ab25225e7be143eeed2";
        }
        PlayerLeaveNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(timestamp, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(timestamp, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerLeaveNotify&l, const PlayerLeaveNotify&r)
    {
        return l.playerId == r.playerId && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerLeaveNotify&l, const PlayerLeaveNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerLeaveNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerLeaveNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct ChatMessage : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.ChatMessage";
        }
        static string MD5()
        {
            return "f1cafe907be0062e20100758cc4c87dd";
        }
        ChatMessage()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            senderId = 0;
            senderName = "";
            content = "";
            channel = 0;
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(senderId, 0);
            _os.write(senderName, 1);
            _os.write(content, 2);
            _os.write(channel, 3);
            _os.write(timestamp, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(senderId, 0, true);
            _is.read(senderName, 1, true);
            _is.read(content, 2, true);
            _is.read(channel, 3, true);
            _is.read(timestamp, 4, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["senderId"] = tars::JsonOutput::writeJson(senderId);
            p->value["senderName"] = tars::JsonOutput::writeJson(senderName);
            p->value["content"] = tars::JsonOutput::writeJson(content);
            p->value["channel"] = tars::JsonOutput::writeJson(channel);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(senderId,pObj->value["senderId"], true);
            tars::JsonInput::readJson(senderName,pObj->value["senderName"], true);
            tars::JsonInput::readJson(content,pObj->value["content"], true);
            tars::JsonInput::readJson(channel,pObj->value["channel"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(senderId,"senderId");
            _ds.display(senderName,"senderName");
            _ds.display(content,"content");
            _ds.display(channel,"channel");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(senderId, true);
            _ds.displaySimple(senderName, true);
            _ds.displaySimple(content, true);
            _ds.displaySimple(channel, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        tars::Int64 senderId;
        std::string senderName;
        std::string content;
        tars::Int32 channel;
        tars::Int64 timestamp;
    };
    inline bool operator==(const ChatMessage&l, const ChatMessage&r)
    {
        return l.senderId == r.senderId && l.senderName == r.senderName && l.content == r.content && l.channel == r.channel && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const ChatMessage&l, const ChatMessage&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const ChatMessage&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,ChatMessage&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct SkillEffect : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.SkillEffect";
        }
        static string MD5()
        {
            return "92669affe1134176b29108d64813b17a";
        }
        SkillEffect()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            casterId = 0;
            targetId = 0;
            skillId = 0;
            damage = 0;
            effectType = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(casterId, 0);
            _os.write(targetId, 1);
            _os.write(skillId, 2);
            _os.write(damage, 3);
            _os.write(effectType, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(casterId, 0, true);
            _is.read(targetId, 1, true);
            _is.read(skillId, 2, true);
            _is.read(damage, 3, true);
            _is.read(effectType, 4, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["casterId"] = tars::JsonOutput::writeJson(casterId);
            p->value["targetId"] = tars::JsonOutput::writeJson(targetId);
            p->value["skillId"] = tars::JsonOutput::writeJson(skillId);
            p->value["damage"] = tars::JsonOutput::writeJson(damage);
            p->value["effectType"] = tars::JsonOutput::writeJson(effectType);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(casterId,pObj->value["casterId"], true);
            tars::JsonInput::readJson(targetId,pObj->value["targetId"], true);
            tars::JsonInput::readJson(skillId,pObj->value["skillId"], true);
            tars::JsonInput::readJson(damage,pObj->value["damage"], true);
            tars::JsonInput::readJson(effectType,pObj->value["effectType"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(casterId,"casterId");
            _ds.display(targetId,"targetId");
            _ds.display(skillId,"skillId");
            _ds.display(damage,"damage");
            _ds.display(effectType,"effectType");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(casterId, true);
            _ds.displaySimple(targetId, true);
            _ds.displaySimple(skillId, true);
            _ds.displaySimple(damage, true);
            _ds.displaySimple(effectType, false);
            return _os;
        }
    public:
        tars::Int64 casterId;
        tars::Int64 targetId;
        tars::Int32 skillId;
        tars::Int32 damage;
        tars::Int32 effectType;
    };
    inline bool operator==(const SkillEffect&l, const SkillEffect&r)
    {
        return l.casterId == r.casterId && l.targetId == r.targetId && l.skillId == r.skillId && l.damage == r.damage && l.effectType == r.effectType;
    }
    inline bool operator!=(const SkillEffect&l, const SkillEffect&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const SkillEffect&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,SkillEffect&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct HeartBeatReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.HeartBeatReq";
        }
        static string MD5()
        {
            return "282dee69d7580ed43b374bb636595df2";
        }
        HeartBeatReq()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
    };
    inline bool operator==(const HeartBeatReq&l, const HeartBeatReq&r)
    {
        return l.playerId == r.playerId;
    }
    inline bool operator!=(const HeartBeatReq&l, const HeartBeatReq&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const HeartBeatReq&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,HeartBeatReq&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct EnterSceneReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.EnterSceneReq";
        }
        static string MD5()
        {
            return "7c0dc944c05c2016ec794c2371a4606b";
        }
        EnterSceneReq()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            sceneId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(sceneId, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(sceneId, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(sceneId,"sceneId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(sceneId, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Int32 sceneId;
    };
    inline bool operator==(const EnterSceneReq&l, const EnterSceneReq&r)
    {
        return l.playerId == r.playerId && l.sceneId == r.sceneId;
    }
    inline bool operator!=(const EnterSceneReq&l, const EnterSceneReq&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const EnterSceneReq&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,EnterSceneReq&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct EnterSceneRsp : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.EnterSceneRsp";
        }
        static string MD5()
        {
            return "1c87459b2bb9dae7ee339e7fb6658895";
        }
        EnterSceneRsp()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            ret = 0;
            msg = "";
            self.resetDefautlt();
            players.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(ret, 0);
            if (msg != "")
            {
                _os.write(msg, 1);
            }
            _os.write(self, 2);
            if (players.size() > 0)
            {
                _os.write(players, 3);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(ret, 0, true);
            _is.read(msg, 1, false);
            _is.read(self, 2, false);
            _is.read(players, 3, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["ret"] = tars::JsonOutput::writeJson(ret);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            p->value["self"] = tars::JsonOutput::writeJson(self);
            p->value["players"] = tars::JsonOutput::writeJson(players);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(ret,pObj->value["ret"], true);
            tars::JsonInput::readJson(msg,pObj->value["msg"], false);
            tars::JsonInput::readJson(self,pObj->value["self"], false);
            tars::JsonInput::readJson(players,pObj->value["players"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(ret,"ret");
            _ds.display(msg,"msg");
            _ds.display(self,"self");
            _ds.display(players,"players");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(ret, true);
            _ds.displaySimple(msg, true);
            _ds.displaySimple(self, true);
            _ds.displaySimple(players, false);
            return _os;
        }
    public:
        tars::Int32 ret;
        std::string msg;
        GameDemo::PlayerInfo self;
        vector<GameDemo::PlayerInfo> players;
    };
    inline bool operator==(const EnterSceneRsp&l, const EnterSceneRsp&r)
    {
        return l.ret == r.ret && l.msg == r.msg && l.self == r.self && l.players == r.players;
    }
    inline bool operator!=(const EnterSceneRsp&l, const EnterSceneRsp&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const EnterSceneRsp&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,EnterSceneRsp&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct MoveReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.MoveReq";
        }
        static string MD5()
        {
            return "50686460be3b7d11bbc122ceda14e777";
        }
        MoveReq()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            x = 0;
            y = 0;
            z = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(x, 1);
            _os.write(y, 2);
            _os.write(z, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(x, 1, true);
            _is.read(y, 2, true);
            _is.read(z, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["z"] = tars::JsonOutput::writeJson(z);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(z,pObj->value["z"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(z,"z");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(z, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Float x;
        tars::Float y;
        tars::Float z;
    };
    inline bool operator==(const MoveReq&l, const MoveReq&r)
    {
        return l.playerId == r.playerId && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && tars::TC_Common::equal(l.z,r.z);
    }
    inline bool operator!=(const MoveReq&l, const MoveReq&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const MoveReq&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,MoveReq&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct MoveRsp : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.MoveRsp";
        }
        static string MD5()
        {
            return "b84e4dd5dd1d7c43dbe702512024405f";
        }
        MoveRsp()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            ret = 0;
            msg = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(ret, 0);
            if (msg != "")
            {
                _os.write(msg, 1);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(ret, 0, true);
            _is.read(msg, 1, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["ret"] = tars::JsonOutput::writeJson(ret);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(ret,pObj->value["ret"], true);
            tars::JsonInput::readJson(msg,pObj->value["msg"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(ret,"ret");
            _ds.display(msg,"msg");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(ret, true);
            _ds.displaySimple(msg, false);
            return _os;
        }
    public:
        tars::Int32 ret;
        std::string msg;
    };
    inline bool operator==(const MoveRsp&l, const MoveRsp&r)
    {
        return l.ret == r.ret && l.msg == r.msg;
    }
    inline bool operator!=(const MoveRsp&l, const MoveRsp&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const MoveRsp&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,MoveRsp&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct LeaveSceneReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.LeaveSceneReq";
        }
        static string MD5()
        {
            return "7c0dc944c05c2016ec794c2371a4606b";
        }
        LeaveSceneReq()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            sceneId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(sceneId, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(sceneId, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(sceneId,"sceneId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(sceneId, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Int32 sceneId;
    };
    inline bool operator==(const LeaveSceneReq&l, const LeaveSceneReq&r)
    {
        return l.playerId == r.playerId && l.sceneId == r.sceneId;
    }
    inline bool operator!=(const LeaveSceneReq&l, const LeaveSceneReq&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const LeaveSceneReq&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,LeaveSceneReq&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct LeaveSceneRsp : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.LeaveSceneRsp";
        }
        static string MD5()
        {
            return "b84e4dd5dd1d7c43dbe702512024405f";
        }
        LeaveSceneRsp()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            ret = 0;
            msg = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(ret, 0);
            if (msg != "")
            {
                _os.write(msg, 1);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(ret, 0, true);
            _is.read(msg, 1, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["ret"] = tars::JsonOutput::writeJson(ret);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(ret,pObj->value["ret"], true);
            tars::JsonInput::readJson(msg,pObj->value["msg"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(ret,"ret");
            _ds.display(msg,"msg");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(ret, true);
            _ds.displaySimple(msg, false);
            return _os;
        }
    public:
        tars::Int32 ret;
        std::string msg;
    };
    inline bool operator==(const LeaveSceneRsp&l, const LeaveSceneRsp&r)
    {
        return l.ret == r.ret && l.msg == r.msg;
    }
    inline bool operator!=(const LeaveSceneRsp&l, const LeaveSceneRsp&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const LeaveSceneRsp&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,LeaveSceneRsp&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct GetScenePlayersRsp : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.GetScenePlayersRsp";
        }
        static string MD5()
        {
            return "ff9ca8c49b0ca25e502929a831e7065a";
        }
        GetScenePlayersRsp()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            ret = 0;
            msg = "";
            players.clear();
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(ret, 0);
            if (msg != "")
            {
                _os.write(msg, 1);
            }
            if (players.size() > 0)
            {
                _os.write(players, 2);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(ret, 0, true);
            _is.read(msg, 1, false);
            _is.read(players, 2, false);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["ret"] = tars::JsonOutput::writeJson(ret);
            p->value["msg"] = tars::JsonOutput::writeJson(msg);
            p->value["players"] = tars::JsonOutput::writeJson(players);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(ret,pObj->value["ret"], true);
            tars::JsonInput::readJson(msg,pObj->value["msg"], false);
            tars::JsonInput::readJson(players,pObj->value["players"], false);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(ret,"ret");
            _ds.display(msg,"msg");
            _ds.display(players,"players");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(ret, true);
            _ds.displaySimple(msg, true);
            _ds.displaySimple(players, false);
            return _os;
        }
    public:
        tars::Int32 ret;
        std::string msg;
        vector<GameDemo::PlayerInfo> players;
    };
    inline bool operator==(const GetScenePlayersRsp&l, const GetScenePlayersRsp&r)
    {
        return l.ret == r.ret && l.msg == r.msg && l.players == r.players;
    }
    inline bool operator!=(const GetScenePlayersRsp&l, const GetScenePlayersRsp&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const GetScenePlayersRsp&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,GetScenePlayersRsp&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


}



#endif
