// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.12.
// **********************************************************************

#ifndef __GAMEDEMOBASE_H_
#define __GAMEDEMOBASE_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;


namespace GameDemo
{
    enum ErrorCode
    {
        SUCCESS = 0,
        ERR_ACCOUNT_NOT_FOUND = 1001,
        ERR_PASSWORD_WRONG = 1002,
        ERR_ROLE_NOT_FOUND = 2001,
        ERR_SCENE_NOT_FOUND = 3001,
        ERR_SERVER_BUSY = 9999,
    };
    inline string etos(const ErrorCode & e)
    {
        switch(e)
        {
            case SUCCESS: return "SUCCESS";
            case ERR_ACCOUNT_NOT_FOUND: return "ERR_ACCOUNT_NOT_FOUND";
            case ERR_PASSWORD_WRONG: return "ERR_PASSWORD_WRONG";
            case ERR_ROLE_NOT_FOUND: return "ERR_ROLE_NOT_FOUND";
            case ERR_SCENE_NOT_FOUND: return "ERR_SCENE_NOT_FOUND";
            case ERR_SERVER_BUSY: return "ERR_SERVER_BUSY";
            default: return "";
        }
    }
    inline int stoe(const string & s, ErrorCode & e)
    {
        if(s == "SUCCESS")  { e=SUCCESS; return 0;}
        if(s == "ERR_ACCOUNT_NOT_FOUND")  { e=ERR_ACCOUNT_NOT_FOUND; return 0;}
        if(s == "ERR_PASSWORD_WRONG")  { e=ERR_PASSWORD_WRONG; return 0;}
        if(s == "ERR_ROLE_NOT_FOUND")  { e=ERR_ROLE_NOT_FOUND; return 0;}
        if(s == "ERR_SCENE_NOT_FOUND")  { e=ERR_SCENE_NOT_FOUND; return 0;}
        if(s == "ERR_SERVER_BUSY")  { e=ERR_SERVER_BUSY; return 0;}

        return -1;
    }

    struct PlayerInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerInfo";
        }
        static string MD5()
        {
            return "b8c87114a8776ca3e9b5f58b2648a738";
        }
        PlayerInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            openId = "";
            roleName = "";
            level = 0;
            x = 0;
            y = 0;
            z = 0;
            sceneId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(openId, 1);
            _os.write(roleName, 2);
            _os.write(level, 3);
            _os.write(x, 4);
            _os.write(y, 5);
            _os.write(z, 6);
            _os.write(sceneId, 7);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(openId, 1, true);
            _is.read(roleName, 2, true);
            _is.read(level, 3, true);
            _is.read(x, 4, true);
            _is.read(y, 5, true);
            _is.read(z, 6, true);
            _is.read(sceneId, 7, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["openId"] = tars::JsonOutput::writeJson(openId);
            p->value["roleName"] = tars::JsonOutput::writeJson(roleName);
            p->value["level"] = tars::JsonOutput::writeJson(level);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["z"] = tars::JsonOutput::writeJson(z);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(openId,pObj->value["openId"], true);
            tars::JsonInput::readJson(roleName,pObj->value["roleName"], true);
            tars::JsonInput::readJson(level,pObj->value["level"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(z,pObj->value["z"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(openId,"openId");
            _ds.display(roleName,"roleName");
            _ds.display(level,"level");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(z,"z");
            _ds.display(sceneId,"sceneId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(openId, true);
            _ds.displaySimple(roleName, true);
            _ds.displaySimple(level, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(z, true);
            _ds.displaySimple(sceneId, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        std::string openId;
        std::string roleName;
        tars::Int32 level;
        tars::Float x;
        tars::Float y;
        tars::Float z;
        tars::Int32 sceneId;
    };
    inline bool operator==(const PlayerInfo&l, const PlayerInfo&r)
    {
        return l.playerId == r.playerId && l.openId == r.openId && l.roleName == r.roleName && l.level == r.level && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && tars::TC_Common::equal(l.z,r.z) && l.sceneId == r.sceneId;
    }
    inline bool operator!=(const PlayerInfo&l, const PlayerInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct SceneInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.SceneInfo";
        }
        static string MD5()
        {
            return "38077dd53b3ea7507376586809fd8b92";
        }
        SceneInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            sceneId = 0;
            sceneName = "";
            playerCount = 0;
            maxPlayer = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sceneId, 0);
            _os.write(sceneName, 1);
            _os.write(playerCount, 2);
            _os.write(maxPlayer, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sceneId, 0, true);
            _is.read(sceneName, 1, true);
            _is.read(playerCount, 2, true);
            _is.read(maxPlayer, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            p->value["sceneName"] = tars::JsonOutput::writeJson(sceneName);
            p->value["playerCount"] = tars::JsonOutput::writeJson(playerCount);
            p->value["maxPlayer"] = tars::JsonOutput::writeJson(maxPlayer);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
            tars::JsonInput::readJson(sceneName,pObj->value["sceneName"], true);
            tars::JsonInput::readJson(playerCount,pObj->value["playerCount"], true);
            tars::JsonInput::readJson(maxPlayer,pObj->value["maxPlayer"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sceneId,"sceneId");
            _ds.display(sceneName,"sceneName");
            _ds.display(playerCount,"playerCount");
            _ds.display(maxPlayer,"maxPlayer");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sceneId, true);
            _ds.displaySimple(sceneName, true);
            _ds.displaySimple(playerCount, true);
            _ds.displaySimple(maxPlayer, false);
            return _os;
        }
    public:
        tars::Int32 sceneId;
        std::string sceneName;
        tars::Int32 playerCount;
        tars::Int32 maxPlayer;
    };
    inline bool operator==(const SceneInfo&l, const SceneInfo&r)
    {
        return l.sceneId == r.sceneId && l.sceneName == r.sceneName && l.playerCount == r.playerCount && l.maxPlayer == r.maxPlayer;
    }
    inline bool operator!=(const SceneInfo&l, const SceneInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const SceneInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,SceneInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerMoveNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerMoveNotify";
        }
        static string MD5()
        {
            return "674e35bea8eedc87261b47e9db8c2493";
        }
        PlayerMoveNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            x = 0;
            y = 0;
            z = 0;
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(x, 1);
            _os.write(y, 2);
            _os.write(z, 3);
            _os.write(timestamp, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(x, 1, true);
            _is.read(y, 2, true);
            _is.read(z, 3, true);
            _is.read(timestamp, 4, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["x"] = tars::JsonOutput::writeJson(x);
            p->value["y"] = tars::JsonOutput::writeJson(y);
            p->value["z"] = tars::JsonOutput::writeJson(z);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(x,pObj->value["x"], true);
            tars::JsonInput::readJson(y,pObj->value["y"], true);
            tars::JsonInput::readJson(z,pObj->value["z"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(x,"x");
            _ds.display(y,"y");
            _ds.display(z,"z");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(x, true);
            _ds.displaySimple(y, true);
            _ds.displaySimple(z, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Float x;
        tars::Float y;
        tars::Float z;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerMoveNotify&l, const PlayerMoveNotify&r)
    {
        return l.playerId == r.playerId && tars::TC_Common::equal(l.x,r.x) && tars::TC_Common::equal(l.y,r.y) && tars::TC_Common::equal(l.z,r.z) && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerMoveNotify&l, const PlayerMoveNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerMoveNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerMoveNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerEnterNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerEnterNotify";
        }
        static string MD5()
        {
            return "fbe6de8dc110a32ba26fec22b22c9ad0";
        }
        PlayerEnterNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            player.resetDefautlt();
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(player, 0);
            _os.write(timestamp, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(player, 0, true);
            _is.read(timestamp, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["player"] = tars::JsonOutput::writeJson(player);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(player,pObj->value["player"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(player,"player");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(player, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        GameDemo::PlayerInfo player;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerEnterNotify&l, const PlayerEnterNotify&r)
    {
        return l.player == r.player && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerEnterNotify&l, const PlayerEnterNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerEnterNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerEnterNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct PlayerLeaveNotify : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.PlayerLeaveNotify";
        }
        static string MD5()
        {
            return "fbee022731165ab25225e7be143eeed2";
        }
        PlayerLeaveNotify()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            playerId = 0;
            timestamp = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(playerId, 0);
            _os.write(timestamp, 1);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(playerId, 0, true);
            _is.read(timestamp, 1, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["playerId"] = tars::JsonOutput::writeJson(playerId);
            p->value["timestamp"] = tars::JsonOutput::writeJson(timestamp);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(playerId,pObj->value["playerId"], true);
            tars::JsonInput::readJson(timestamp,pObj->value["timestamp"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(playerId,"playerId");
            _ds.display(timestamp,"timestamp");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(playerId, true);
            _ds.displaySimple(timestamp, false);
            return _os;
        }
    public:
        tars::Int64 playerId;
        tars::Int64 timestamp;
    };
    inline bool operator==(const PlayerLeaveNotify&l, const PlayerLeaveNotify&r)
    {
        return l.playerId == r.playerId && l.timestamp == r.timestamp;
    }
    inline bool operator!=(const PlayerLeaveNotify&l, const PlayerLeaveNotify&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const PlayerLeaveNotify&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,PlayerLeaveNotify&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }

    struct RoleInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "GameDemo.RoleInfo";
        }
        static string MD5()
        {
            return "f795919e3e57f5eef1d95b85082a837e";
        }
        RoleInfo()
        {
            resetDefautlt();
        }
        void resetDefautlt()
        {
            roleId = 0;
            roleName = "";
            level = 0;
            sceneId = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(roleId, 0);
            _os.write(roleName, 1);
            _os.write(level, 2);
            _os.write(sceneId, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(roleId, 0, true);
            _is.read(roleName, 1, true);
            _is.read(level, 2, true);
            _is.read(sceneId, 3, true);
        }
        tars::JsonValueObjPtr writeToJson() const
        {
            tars::JsonValueObjPtr p = new tars::JsonValueObj();
            p->value["roleId"] = tars::JsonOutput::writeJson(roleId);
            p->value["roleName"] = tars::JsonOutput::writeJson(roleName);
            p->value["level"] = tars::JsonOutput::writeJson(level);
            p->value["sceneId"] = tars::JsonOutput::writeJson(sceneId);
            return p;
        }
        string writeToJsonString() const
        {
            return tars::TC_Json::writeValue(writeToJson());
        }
        void readFromJson(const tars::JsonValuePtr & p, bool isRequire = true)
        {
            resetDefautlt();
            if(NULL == p.get() || p->getType() != tars::eJsonTypeObj)
            {
                char s[128];
                snprintf(s, sizeof(s), "read 'struct' type mismatch, get type: %d.", (p.get() ? p->getType() : 0));
                throw tars::TC_Json_Exception(s);
            }
            tars::JsonValueObjPtr pObj=tars::JsonValueObjPtr::dynamicCast(p);
            tars::JsonInput::readJson(roleId,pObj->value["roleId"], true);
            tars::JsonInput::readJson(roleName,pObj->value["roleName"], true);
            tars::JsonInput::readJson(level,pObj->value["level"], true);
            tars::JsonInput::readJson(sceneId,pObj->value["sceneId"], true);
        }
        void readFromJsonString(const string & str)
        {
            readFromJson(tars::TC_Json::getValue(str));
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(roleId,"roleId");
            _ds.display(roleName,"roleName");
            _ds.display(level,"level");
            _ds.display(sceneId,"sceneId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(roleId, true);
            _ds.displaySimple(roleName, true);
            _ds.displaySimple(level, true);
            _ds.displaySimple(sceneId, false);
            return _os;
        }
    public:
        tars::Int64 roleId;
        std::string roleName;
        tars::Int32 level;
        tars::Int32 sceneId;
    };
    inline bool operator==(const RoleInfo&l, const RoleInfo&r)
    {
        return l.roleId == r.roleId && l.roleName == r.roleName && l.level == r.level && l.sceneId == r.sceneId;
    }
    inline bool operator!=(const RoleInfo&l, const RoleInfo&r)
    {
        return !(l == r);
    }
    inline ostream& operator<<(ostream & os,const RoleInfo&r)
    {
        os << r.writeToJsonString();
        return os;
    }
    inline istream& operator>>(istream& is,RoleInfo&l)
    {
        std::istreambuf_iterator<char> eos;
        std::string s(std::istreambuf_iterator<char>(is), eos);
        l.readFromJsonString(s);
        return is;
    }


}



#endif
